version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../deployment/docker/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge