version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../deployment/docker/backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/drone-delivery
      - JWT_SECRET=change_this_in_production
      - PORT=5000
    networks:
      - drone-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../deployment/docker/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - drone-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - drone-network

  drone-simulator:
    build:
      context: ./drone
      dockerfile: ../deployment/docker/drone-simulator/Dockerfile
    depends_on:
      - backend
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge

volumes:
  mongodb_data:
